inmakes_products/movieeproject/movieeapp/urls.py
from . import views
from django.urls import path

app_name = 'movieeapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')

]

inmakes_products/movieeproject/movieeproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieeapp.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inmakes_products/movieeproject/movieeapp/models.py
from django.db import models


# Create your models here.
class movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')


def __str__(self):
    return self.name

inmakes_products/movieeproject/movieeapp/forms.py
from django import forms
from .models import movie


class movieform(forms.ModelForm):
    class Meta:
        model = movie
        fields = ['name', 'desc', 'year', 'img']

inmakes_products/movieeproject/movieeapp/views.py
from django.shortcuts import render, redirect
from movieeapp.models import movie
from .forms import movieform
def index(request):
    Movie = movie.objects.all()
    context = {
        'movie_list': Movie
    }
    return render(request, 'index.html', context)
def detail(request, movie_id):
    Movie = movie.objects.get(id=movie_id)
    return render(request, "detail.html", {'movie': Movie})
def add_movie(request):
    if request.method == "POST":
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        Movie = movie(name=name, desc=desc, year=year, img=img)
        Movie.save()
    return render(request, 'add.html')
def update(request, id):
    Movie = movie.objects.get(id=id)
    form = movieform(request.POST or None, request.FILES, instance=Movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': Movie})
def delete(request, id):
    if request.method == "POST":
        Movie = movie.objects.get(id=id)
        Movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

inmakes_products/movieeproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter Movie Name"><br><br>
    <input type="text" name="desc" placeholder="Enter Movie Description"><br><br>
    <input type="text" name="year" placeholder="Enter Movie Year"><br><br>
    <input type="file" name="img">
    <input type="submit">
</form>
{% endblock %}

inmakes_products/movieeproject/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark  bg-dark">
  <a class="navbar-brand" href="#">
   Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

inmakes_products/movieeproject/templates/delete.html
<form method="post">
    {% csrf_token %}
    Are you want to delete this Movie?<br>
    <input type="submit">
</form>

inmakes_products/movieeproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300"><br>
        </div>
        <div class="col-md-6">
            <h2>{{movie.name}}</h2><br>
            <h4>{{movie.desc}}</h4><br>
            <h5>{{movie.year}}</h5><br>
            <a class="btn btn-warning" href="{% url 'movieeapp:update' movie.id %}">
                    Update
            </a>
            <a class="btn btn-danger" href="{% url 'movieeapp:delete' movie.id %}">
                     Delete
            </a>
        </div>
    </div>
</div>


{% endblock %}

inmakes_products/movieeproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

inmakes_products/movieeproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
         <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3"><br>
            <div class="card" width="500" height="300">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="300" height="300" >
                    <div class="card-body">
                         <h5 class="card-title">{{i.name}}</h5>
                                <a href="{% url 'movieeapp:detail' i.id %}" class="btn btn-primary">Go Detail</a><br>
                     </div>
            </div>
        </div>
    {% endfor %}
    </div>

</div>
{% endblock %}